framework:
    messenger:
        transports:
             async: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Message\GenerateUserJob: async
            App\Message\GeneratePostJob: async
