controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: /api
    name_prefix: api_
    options:
        expose: true

kernel:
    resource: ../../src/Kernel.php
    type: annotation
